// Polls /live.json (regenerated by the backend pipeline as the detector processes the
// video) and updates the dashboard IN PLACE — ported from js/app.js pollLive(). No-ops
// when live.json is absent (static hosting).
import { DATA } from './data.js';
import { issues, wardScores, SCORES } from './model.js';
import { notify } from './store.js';
import { showToast } from './liveToast.js';
import i18next from '../i18n/index.js';

let liveRev = null;

export async function pollLive() {
  try {
    const r = await fetch('/live.json?_=' + Date.now(), { cache: 'no-store' });
    if (!r.ok) return;
    const p = await r.json();
    if (!p || !Array.isArray(p.issues) || p.rev === liveRev) return;
    const first = liveRev === null;
    liveRev = p.rev;
    const prevLive = issues.filter(i => i.runId).length;
    const seed = issues.filter(i => !i.runId); // keep seed + officer edits (no runId)
    issues.length = 0; issues.push(...seed, ...p.issues);
    if (Array.isArray(p.replay)) DATA.replay_ids = p.replay;
    Object.assign(SCORES, wardScores());
    if (first) { notify(); return; } // silent sync at startup
    const added = p.issues.length - prevLive;
    const statusLabel = i18next.t(p.partial ? 'liveToast.processingVideo' : 'liveToast.processingComplete');
    showToast(
      `<span class="dot"></span> ${statusLabel} · <b>${p.issues.length}</b> detections`
      + (added > 0 ? ` · <span style="color:#8fd39a">${i18next.t('liveToast.newDetections', { count: added })}</span>` : '')
    );
    notify();
  } catch (e) { /* live.json not served — ignore */ }
}

export function startLivePolling() {
  pollLive();
  const id = setInterval(pollLive, 8000);
  return () => clearInterval(id);
}
